import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "../CommonComponent/websiteCommonComponent/Header";
import Footer from "../CommonComponent/websiteCommonComponent/Footer";
import LoginContext from "../Context/LoginContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoginContext>
        <Header/>
        {children}
        <Footer/>
        </LoginContext>
      
      </body>
     
    </html>
  );
}
